service: my-serverless-app

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 256
 timeout: 10
 stage: production
 region: us-east-2

functions:
 api:
   handler: lambda.universal
   events:
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY


